### ISSUE TITLE
search and test apis -

### ISSUE THREAD

**Issue by axeljamal** [babyleezus/travel-concierge-api-project#5]
[Food APIs (Free Tutorials, SDKs, API Keys, Documentation & More) | RapidAPI](https://rapidapi.com/category/Food)

https://research.aimultiple.com/travel-api/

https://developer.trekksoft.com/#tag/Activities/paths/~1activities/get

Map - https://rapidapi.com/MapTilesApi/api/maptiles/ ~ Working

Translate - https://rapidapi.com/googlecloud/api/google-translate1 ~ Working

Restaurants - https://rapidapi.com/DataCrawler/api/tripadvisor16/ ~ Working

**Comment by ReneeDanielleB** [comment]
Added map, translate & restaurants apis to javascript
